### ISSUE TITLE
Never reaches following code every second time

### ISSUE THREAD

**Issue by Yuripetusko** [halt-hammerzeit/webpack-isomorphic-tools#108] opened 2016-09-23 14:50 UTC
Hello you are free to close this issue if not enough information provided, 

We are seeing this issue ~every second deploy

```
global.webpackIsomorphicTools = new WebpackIsomorphicTools(webpackIsomorphicAssets)
  .development(!serverConfig.isProduction)
  .server(rootDir, () => {
    console.log('Reached here 2');
    require('./main.js');
  });
```

this `console.log` always fires, but in `main.js` at the very top of the file there is another `console.log` which doesn't fire every second time and our deployment fails due to timeout. Any idea why this might happen?

**Comment by halt-hammerzeit** [comment] 2016-09-23 15:46
That's very strange.
That shouldn't be possible.
I'll close this for now, but if you happen to find the cause of the error then you may reopen this issue.

One assumption is that `require('./main.js')` isn't really what you think it is.
`webpack-isomorphic-tools` instrument Node.js'es `require()` function with its own code, so it may be failing there and never actually executing your `./main.js` file.
I suggest you enable `debug: true` flag and see what it outputs to the console when the bug is reproduced.

**Closed by halt-hammerzeit** 2016-09-23 15:46 UTC

**Comment by Yuripetusko** [comment] 2016-09-23 15:49
@halt-hammerzeit ok I did enable debug:true and looks like in production it requires all our .styl files, when this is firing

```
global.webpackIsomorphicTools = new WebpackIsomorphicTools(webpackIsomorphicAssets)
  .development(!serverConfig.isProduction)
  .server(rootDir, () => {
    console.log('Reached here 2', rootDir);
    require('./main.js');
  });
```

And we have so many files so the actual server never starts before heroku 60 seconds timeout expires, why is it requiring all the files from our assets config, i thought they should be pre-compiled.

Also as I noted before it is happening every second time, so it's not because of requiring main.js is wrong.

**Comment by Yuripetusko** [comment] 2016-09-23 15:50
so debug looks something like that:

```
...

Sep 23 08:33:22 bridebook-dev app/web.1:  [App:server] [webpack-isomorphic-tools] [debug] require() called for /app/src/browser/dashboard/DetailsMobile.styl 
Sep 23 08:33:22 bridebook-dev app/web.1:  [App:server] [webpack-isomorphic-tools] [debug]  requiring ./src/browser/dashboard/DetailsMobile.styl 
Sep 23 08:33:22 bridebook-dev app/web.1:  [App:server] [require-hacker] [debug] require() hook fired for /app/src/browser/shortlist/Shortlist.styl 
Sep 23 08:33:22 bridebook-dev app/web.1:  [App:server] [webpack-isomorphic-tools] [debug] require() called for /app/src/browser/shortlist/Shortlist.styl 
Sep 23 08:33:22 bridebook-dev app/web.1:  [App:server] [webpack-isomorphic-tools] [debug]  requiring ./src/browser/shortlist/Shortlist.styl 
Sep 23 08:33:22 bridebook-dev app/web.1:  [App:server] [require-hacker] [debug] require() hook fired for /app/src/browser/shortlist/Block.styl 
Sep 23 08:33:22 bridebook-dev app/web.1:  [App:server] [webpack-isomorphic-tools] [debug] require() called for /app/src/browser/shortlist/Block.styl 
Sep 23 08:33:22 bridebook-dev app/web.1:  [App:server] [webpack-isomorphic-tools] [debug]  requiring ./src/browser/shortlist/Block.styl 
Sep 23 08:33:22 bridebook-dev heroku/web.2:  Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch 
```

**Comment by Yuripetusko** [comment] 2016-09-23 15:55
So my question is I guess, why is it requiring all those files in production mode, and how to avoid it, we do precompile all the assets with webpack with gulp, before starting a server

**Comment by halt-hammerzeit** [comment] 2016-09-23 16:07
It `require()`s assets only when it's told to do so.
It doesn't do that by itself.
I don't know why it does that after `console.log('Reached here 2', rootDir);` and before the first line of `main.js`.

**Comment by Yuripetusko** [comment] 2016-09-23 17:33
I kinda know where the issue is now, not sure how to fix it yet. When I start my express server it requires `createRoutes` which bootstraps react router, this file requires whole bunch of react components which has imports of stylus files, so this means I am requring bunch of files with stylus files even before express server starts and binds to port, so `webpack-isomorphic-tools` starts requiring and processing those files synchroniously I guess, so my server never starts in time before heroku timeout expires

**Comment by halt-hammerzeit** [comment] 2016-09-23 18:13
Ideally you should not `require()` anything outside `webpack-isomorphic-tools` `.server()` method

**Comment by Yuripetusko** [comment] 2016-09-23 18:22
Not sure what you mean. It's a chain reaction really. I have this code.

```
global.webpackIsomorphicTools = new WebpackIsomorphicTools(webpackIsomorphicAssets)
  .development(!serverConfig.isProduction)
  .server(rootDir, () => {
    console.log('Reached here 2', rootDir);
    require('./main.js');
  });
```

in `main.js` I set up my express server and one of the middlewares for my `*` route requires a react component which imports whole bund of stylus files, 

so let's say my main.js looks likee this:

```
...

import render from './render';
app.get('*', render);
app.listen(port, () => {
  console.log('Server started at port %d', port);
});
```
Now `render.js` imports a module called `createRoutes` which imports my high level react components for each page on our website, each of these components imports stylus files.

So following this chain when I do `require('./main.js');` in the beginning, `webpack-isomorphic-tools` spots all these stylus files imports and starts proccessing and caching them which slows down the actual `app.listen`

**Comment by halt-hammerzeit** [comment] 2016-09-23 18:24
Oh, I see now: it's a heroku specufic issue when it shuts down the app if
it doesn't listen in a minute.

**Comment by Yuripetusko** [comment] 2016-09-23 18:25
@halt-hammerzeit yes exactly

**Comment by Yuripetusko** [comment] 2016-09-23 18:26
So I am thinking on how to pre-cache all the files before starting a server, or maybe refactor the app so all my requires happen after server has started

**Comment by Yuripetusko** [comment] 2016-09-23 18:29
But even without it being a heroku issue, it's a bit worrying that this way the memmory usage is around 600mb because we fetch/proccess/cache so many asset files in one go and also firing a server. Still thinking on how to optimise it

**Comment by halt-hammerzeit** [comment] 2016-09-23 18:32
Well, if your assets are huge there's no way around it.
Alternatively you can require inside render() and then clear require.cache

**Comment by catamphetamine** [comment] 2018-03-02 12:49
@Yuripetusko 
> Still thinking on how to optimise it

It can be optimized using `universal-webpack` instead of `webpack-isomorphic-tools` and then using `ExtractTextPlugin` to move styles from `.js` files to a separate big `.css` file.
In production it shouldn't not use `ExtractTextPlugin` I guess.

**Comment by Yuripetusko** [comment] 2018-03-02 12:52
@brotzky I don't remember if we solved it, but we since migrated to Nextjs which has SSR solution built in

**Comment by catamphetamine** [comment] 2018-03-02 12:53
@brotzky I also recommend Next.js for starters

**Comment by brotzky** [comment] 2018-03-02 17:14
Thanks!

I think I'll try moving out code base over to `universal-webpack`. I've used `webpack-isomorphic-tools` before and it wasn't an issue, but that project didn't use `ExtractTextPlugin` since it was purely Styled Components. 

`Nextjs` doesn't provide our project enough flexibility, but I have used it on small personal side projects and it has been great!

**Comment by catamphetamine** [comment] 2018-03-02 17:36
@brotzky Feel free to ask questions on `universal-webpack` in a new thread in that repo.
It's not that hard to set up.
Consult the example project for reference.
