### ISSUE TITLE
composing css modules throws error

### ISSUE THREAD

**Issue by bdefore** [halt-hammerzeit/webpack-isomorphic-tools#1] opened 2015-08-20 14:40 UTC
I'm working with @erikras redux boilerplate which recently integrated webpack-isomorphic-tools and I've noticed that I cannot use the `composes` feature of `css-loader` as documented here: https://github.com/webpack/css-loader#composing-css-classes. In order to use flexboxgrid, a responsive styling library, I would like add the following to my App.scss:

```
:local(.appContainer) {
  composes: row from 'flexboxgrid/dist/flexboxgrid.css';
  margin: 20px;
}
```

But I get the following error:

```
[0] /[REDACTED]/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/plugin/write assets.js:202
[0]         throw _iteratorError;
[0]               ^
[0] SyntaxError: Unexpected token +
[0]     at Object.parse (native)
```

Full error gist is here: https://gist.github.com/bdefore/60b3206cc2a57b87116b

**Comment by halt-hammerzeit** [comment] 2015-08-20 14:45
So, what's on the line 47 then?
  
`/[REDACTED]/webpack/webpack-isomorphic-tools.js:47:42`

Anyway, the error is in your `parser` function.
So you should provide it's source code.
It even says that in the second line of the error stack.

**Comment by bdefore** [comment] 2015-08-20 14:48
That file is unchanged from the version you provided in your PR. It's where a `JSON.parse` call is made: https://github.com/erikras/react-redux-universal-hot-example/blob/master/webpack/webpack-isomorphic-tools.js

**Comment by bdefore** [comment] 2015-08-20 14:49
The same error appears to occur when loading in a file from a relative path such as:

```
:local(.appContainer) {
  composes: foo from './Home.scss';
  margin: 20px;
}
```

**Comment by erikras** [comment] 2015-08-20 14:50
Maybe put a `console.log(match)` before that line 47 to see what it's trying to parse?

**Comment by halt-hammerzeit** [comment] 2015-08-20 14:50
Well, this issue is surely unrelated to `webpack-isomorphic-tools` as far as I can tell.
As far as I understood this is the issue with the `parser` function.
And I have no idea what it does actually

**Comment by halt-hammerzeit** [comment] 2015-08-20 14:51
Yeah, try to output the match object.
Something like

```javascript
options.log.info('match', match[1])
```

**Comment by bdefore** [comment] 2015-08-20 14:55
Using the simpler version above, using Home.scss, a `console.log('match', match[1])` yields:

```
[0] match {
[0] 	"appContainer": "appContainer___18ST9 " + require("-!./../../node_modules/css-loader/index.js?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!./../../node_modules/autoprefixer-loader/index.js?browsers=last 2 version!./../../node_modules/sass-loader/index.js?outputStyle=expanded&sourceMap!./Home.scss").locals["foo"] + ""
[0] }
```

It looks like it's trying to append something incorrectly.

**Comment by halt-hammerzeit** [comment] 2015-08-20 14:57
Yeah, no way concatenation is allowed in JSON format spec.

**Comment by halt-hammerzeit** [comment] 2015-08-20 14:57
Actually it's not JSON anymore - it's javascript.
So maybe use `eval()` or something like that?

**Comment by halt-hammerzeit** [comment] 2015-08-20 14:59
I'll close the issue because you've found the root of the problem.
You are free to continue your discussion here though.

**Closed by halt-hammerzeit** 2015-08-20 14:59 UTC

**Comment by bdefore** [comment] 2015-08-20 15:39
If I change the parser in the configuration file to use `parser: WebpackIsomorphicToolsPlugin.url_loader_parser` even for styles_module, rather than the JSON.parse approach, it appears to function correctly. This function currently does some string manipulation, splicing things together around double quotes:

```
	// retain everything inside of double quotes.
	// usually it's "data:image..." for embedded with the double quotes
	// or __webpack_public_path__ + "..." for filesystem path
	var double_qoute_index = module.source.indexOf('"');
	var asset_path = module.source.slice(double_qoute_index + 1, -1);
```

 I tried to bring that logic into the other method but was unsuccessful.

Replacing the parser entirely makes me wonder if it's not correctly going to pick up the correct Webpack configuration depending on environment. @erikras do you think that will be the case?

**Comment by halt-hammerzeit** [comment] 2015-08-20 16:07
I don't actually understand what you are talking about here, but I as far as I can tell the issue is arising only if you use a particular feature of style modules. To be more specific, the compose feature (I don't know what it does though).
Therefore, I guess, using the compose feature makes `css-loader` change its output and it becomes non JSON-parseable.
This parser function for css-modules is a fragile thing and of course it can break on any new use case.
I think that's the case here.

**Comment by halt-hammerzeit** [comment] 2016-05-21 17:25
FYI
I'm posting this in every issue and PR to notify whoever may be interested:
today I've released an alternative helper library called [`universal-webpack`](https://github.com/halt-hammerzeit/universal-webpack).
It takes a different approach than `webpack-ismorphic-tools` and instead of hacking Node.js `require()` calls it just compiles all code with `target: 'node'` webpack configuration option.
As a result, all Webpack plugins and features are supported.
If you think you might need that here's an example project:
https://github.com/halt-hammerzeit/webpack-react-redux-isomorphic-render-example
